# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('expiredTime', models.DateTimeField()),
            ],
        ),
    ]
