# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('salt', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('member', 'member'), ('admin', 'admin')], default='member', max_length=10)),
            ],
        ),
    ]
