# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('member', 'member'), ('admin', 'admin')], default='member', max_length=10),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='person',
            name='salt',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
